# Generated by Django 4.1.7 on 2023-06-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('image', models.ImageField(upload_to='pics')),
                ('offer', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'travel',
            },
        ),
    ]
